fftree/urls.py
from django.conf.urls import url

from . import views

app_name = 'fftree'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^class/(?P<init_year>[0-9]+)/$', views.pledgeClass, name='pledgeClass'),
	url(r'^brother/(?P<brother_id>[0-9]+)/$', views.brother, name='brother'),
	url(r'^brother/(?P<brother_id>[0-9]+)/comment/$', views.comment, name='comment'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('fftree.urls')),
    url(r'^admin/', admin.site.urls),
]

fftree/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Brother(models.Model):
	name = models.CharField(max_length=200)
	grad_year = models.IntegerField(default=0)
	init_year = models.IntegerField(default=0)
	# add bigbrother id list field
	# add littlebrother id list field
	# add fields for images? links? etc.

	def __str__(self):
		return self.name

fftree/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Brother

# Create your views here.
def index(request):
	brother_list = Brother.objects.order_by('-init_year')
	context = {'brother_list': brother_list,}
	return render(request, 'fftree/index.html', context)

def pledgeClass(request, init_year):
	return HttpResponse("You're looking at brothers in the %s pledge class." % init_year)

def brother(request, brother_id):
	#return HttpResponse("You're looking at brother %s." % brother_id)
	#try:
	#	brother = Brother.objects.get(pk=brother_id)
	#except Brother.DoesNotExist:
	#	raise Http404("Brother does not exist")
	#return render(request, 'fftree/brother.html', {'brother': brother})
	brother = get_object_or_404(Brother, pk=brother_id)
	return render(request, 'fftree/brother.html', {'brother': brother})

def comment(request, brother_id):
	return HttpResponse("You're commenting on brother %s." % brother_id)

fftree/templates/fftree/brother.html
{% load static %}

<h1>{{ brother.name }}</h1>
<div>
	<img src="{% static 'fftree/images/sad.png' %}" height="50%">
</div>
<p>Graduated {{ brother.grad_year }}</p>
<p>Initiated {{ brother.init_year }}</p>

<!-- Add a form eventually, once know what I should put there. Maybe comments or something
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'fftree:comment' brother.id %}" method="post">
	{% csrf_token %}
	<input type="text"-->

<!-- Figure out how to add a custom image based on brother.id, also figure out how to access parameters in the javascript page -->

fftree/templates/fftree/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'fftree/style.css' %}"

{% if brother_list %}
<ul>
	{% for brother in brother_list %}
	<li><a href="{% url 'fftree:brother' brother.id %}">{{ brother.name }}, {{ brother.grad_year }}</a></li>
	{% endfor %}
</ul>
{% else %}
<p> No brothers available.</p>
{% endif %}